-- ---------------------------------------------------------------------------
-- V1: initial schema
--
-- book_edition holds the bibliographic identity keyed by ISBN, book_copy holds
-- the individual physical copies. Splitting them is what makes the two ISBN
-- rules from the spec structurally true rather than merely checked in code:
--   * same ISBN, different title/author  -> impossible, one row per ISBN
--   * same title/author, different ISBN  -> two independent editions
--   * many copies of one ISBN            -> many book_copy rows, distinct ids
-- ---------------------------------------------------------------------------

CREATE TABLE borrower (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(320) NOT NULL
);

-- Email is the natural business key for a member; enforced case-insensitively.
CREATE UNIQUE INDEX ux_borrower_email ON borrower (LOWER(email));

CREATE TABLE book_edition (
    isbn   VARCHAR(13)  NOT NULL PRIMARY KEY,
    title  VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL
);

CREATE INDEX ix_book_edition_title  ON book_edition (LOWER(title));
CREATE INDEX ix_book_edition_author ON book_edition (LOWER(author));

CREATE TABLE book_copy (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(13) NOT NULL REFERENCES book_edition (isbn)
);

CREATE INDEX ix_book_copy_isbn ON book_copy (isbn);

CREATE TABLE borrow_record (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_copy_id BIGINT      NOT NULL REFERENCES book_copy (id),
    borrower_id  BIGINT      NOT NULL REFERENCES borrower (id),
    borrowed_at  TIMESTAMPTZ NOT NULL,
    returned_at  TIMESTAMPTZ,
    CONSTRAINT ck_borrow_record_returned_after_borrowed
        CHECK (returned_at IS NULL OR returned_at >= borrowed_at)
);

-- THE invariant: at most one *open* loan per copy. Returned rows have a non-null
-- returned_at and drop out of the index, so a copy can be lent out again and the
-- full lending history is still preserved.
CREATE UNIQUE INDEX ux_borrow_record_active_copy
    ON borrow_record (book_copy_id)
    WHERE returned_at IS NULL;

CREATE INDEX ix_borrow_record_borrower_active
    ON borrow_record (borrower_id)
    WHERE returned_at IS NULL;
